"""
Simple ttkbootstrap dashboard scaffold demo for Bookstocker.
Run with:
    python -m Bookstocker.dashboard_ttk
or
    python Bookstocker/dashboard_ttk.py

Uses placeholder images in `assets/` generated by `tools/generate_placeholders.py`.
"""
import tkinter as tk
import ttkbootstrap as tb
from ttkbootstrap.constants import LEFT
from PIL import Image, ImageTk
from pathlib import Path

ASSETS = Path(__file__).resolve().parents[0] / "assets"
CUSTOM_BUTTON_SIZE = (320, 64)

CARD_BG = "#f7fafc"


def load_image(name, size=None):
    path = ASSETS / name
    if not path.exists():
        return None
    img = Image.open(path).convert("RGBA")
    if size:
        img = img.resize(size, Image.LANCZOS)
    return ImageTk.PhotoImage(img)


class DashboardDemo(tb.Window):
    def __init__(self):
        super().__init__(title="Bookstocker — Dashboard Demo", themename="flatly")
        self.geometry("1100x680")
        self.minsize(900, 600)
        self._images = {}
        self._load_assets()
        self._build_ui()

    def _load_assets(self):
        names = [
            "logo.png",
            "avatar.png",
            "icon_dashboard.png",
            "icon_inventory.png",
            "icon_orders.png",
            "icon_purchase.png",
            "icon_reporting.png",
            "icon_support.png",
            "icon_settings.png",
            "icon_logout.png",
            "stat_total.png",
            "stat_orders.png",
            "stat_stock.png",
            "stat_out.png",
            "btn_primary.png",
            "buttons/btn_primary.png",
            "buttons/btn_primary_hover.png",
            "buttons/btn_primary_active.png",
        ]
        for n in names:
            if n.startswith("buttons/"):
                img = load_image(n, size=CUSTOM_BUTTON_SIZE)
            else:
                img = load_image(n)
            if img:
                self._images[n] = img

    def _make_image_sidebar_button(self, parent, text):
        normal = self._images.get("buttons/btn_primary.png")
        hover = self._images.get("buttons/btn_primary_hover.png", normal)
        active = self._images.get("buttons/btn_primary_active.png", hover)

        if not normal:
            b = tb.Button(parent, text=text, bootstyle="info")
            b.pack(fill="x", pady=4, padx=6)
            return b

        b = tk.Label(
            parent,
            image=normal,
            cursor="hand2",
            bd=0,
        )
        b.image = normal

        def on_enter(_event):
            b.configure(image=hover)
            b.image = hover

        def on_leave(_event):
            b.configure(image=normal)
            b.image = normal

        def on_press(_event):
            b.configure(image=active)
            b.image = active

        def on_release(_event):
            b.configure(image=hover)
            b.image = hover

        b.bind("<Enter>", on_enter)
        b.bind("<Leave>", on_leave)
        b.bind("<ButtonPress-1>", on_press)
        b.bind("<ButtonRelease-1>", on_release)
        b.pack(anchor="w", pady=4, padx=6)
        return b

    def _build_ui(self):
        # main frames
        container = tb.Frame(self, padding=8)
        container.pack(fill="both", expand=True)
        container.columnconfigure(1, weight=1)
        # sidebar
        sidebar = tb.Frame(container, width=420)
        sidebar.grid(row=0, column=0, sticky="nsw", padx=(0, 8))
        sidebar.pack_propagate(False)

        if "logo.png" in self._images:
            lbl = tb.Label(sidebar, image=self._images["logo.png"]) 
            lbl.pack(pady=(8, 16))
        else:
            tb.Label(sidebar, text="Bookstocker", font=(None, 16, "bold")).pack(pady=(8, 16))

        # nav buttons
        nav_items = [
            ("Dashboard", "icon_dashboard.png"),
            ("Requests", "icon_inventory.png"),
            ("Shipment", "icon_orders.png"),
            ("Batch", "icon_purchase.png"),
            ("Stock", "icon_reporting.png"),
        ]
        for i, (text, icon) in enumerate(nav_items):
            if icon in self._images:
                b = tb.Button(sidebar, text=text, image=self._images[icon], compound=LEFT, bootstyle="light")
            else:
                b = tb.Button(sidebar, text=text, bootstyle="light", width=24)
            b.pack(fill="x", pady=6, padx=8)


        # top + content area
        main = tb.Frame(container)
        main.grid(row=0, column=1, sticky="nsew")
        main.columnconfigure(0, weight=2)
        main.columnconfigure(1, weight=1)
        main.rowconfigure(2, weight=1)

        # header with greeting
        header = tb.Frame(main)
        header.grid(row=0, column=0, columnspan=2, sticky="ew", pady=(0, 8))
        header.columnconfigure(0, weight=1)
        title = tb.Label(header, text="Hi, User", font=(None, 20, "bold"))
        title.grid(row=0, column=0, sticky="w")

        # stat cards grid (4 columns)
        cards = tb.Frame(main)
        cards.grid(row=1, column=0, columnspan=2, sticky="nsew", pady=(0, 8))
        for i in range(4):
            cards.columnconfigure(i, weight=1)

        stats = [
            ("Total Books in Stock", "00"),
            ("Total Batches", "00"),
            ("Batches in Shipment", "00"),
            ("Requested Books", "00"),
        ]
        for idx, (label, val) in enumerate(stats):
            f = tb.Frame(cards, padding=10, bootstyle="light")
            f.grid(row=0, column=idx, padx=6, sticky="nsew")
            tb.Label(f, text=val, font=(None, 20, "bold")).pack(anchor="w")
            tb.Label(f, text=label, font=(None, 10)).pack(anchor="w")
            tb.Button(f, text="View", bootstyle="info").pack(anchor="w", pady=(6, 0))

        # content area below (left large + right sidebar)
        content = tb.Frame(main)
        content.grid(row=2, column=0, columnspan=2, sticky="nsew", pady=(0, 0))
        content.columnconfigure(0, weight=2)
        content.columnconfigure(1, weight=1)

        # left large card (display total books per batch)
        left_card = tb.Frame(content, padding=12, bootstyle="light")
        left_card.grid(row=0, column=0, sticky="nsew", padx=(0, 6))
        tb.Label(left_card, text="Display Total Books per Batch here", font=(None, 12, "bold")).pack(anchor="w", expand=True)

        # right sidebar: requested books
        right_card = tb.Frame(content, padding=12, bootstyle="light")
        right_card.grid(row=0, column=1, sticky="nsew")
        tb.Label(right_card, text="Requested Books", font=(None, 14, "bold")).pack(anchor="w", pady=(0, 8))
        
        # sample requested books
        books_frame = tb.Frame(right_card)
        books_frame.pack(fill="both", expand=True)
        for i in range(3):
            book_item = tb.Frame(books_frame, padding=6, bootstyle="secondary")
            book_item.pack(fill="x", pady=4)
            tb.Label(book_item, text=f"Book Title {i+1}", font=(None, 10, "bold")).pack(anchor="w")
            tb.Label(book_item, text="paperback", font=(None, 8)).pack(anchor="w")

        # footer / hint
        tb.Label(self, text="Demo UI — replace assets in `assets/` with your images").pack(side="bottom", pady=6)


def run():
    app = DashboardDemo()
    app.mainloop()


if __name__ == "__main__":
    run()
